### ISSUE TITLE
Error when trying to reach the OAuth on Harvest

### ISSUE THREAD

**Issue by jacquesbh** [jolicode/forecast-tools#21]
**Describe the bug**
After clicking the "Connect with Forecast" button on Homepage we get the `Invalid redirect_uri is given` message from Harvest OAuth.

![image](https://user-images.githubusercontent.com/858611/78181991-9cd5d600-7465-11ea-9aed-8190cb44c02d.png)

**To Reproduce**
1. Go to <https://forecast.jolicode.com/>
2. Click on "🔒Connect with Forecast"
3. See error

**Expected behavior**
Access to the OAuth page on Harvest.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by xavierlacot** [comment]
This bug does not seem to happen anymore. I guess it was a temporary glitch on Harvest's side. Can you please check?

**Comment by jacquesbh** [comment]
I confirm.
