### ISSUE TITLE
Suggestion: automatically set my Slack status based on specific projets (time off, training...)

### ISSUE THREAD

**Issue by damienalexandre** [jolicode/forecast-tools#39]
Slack personal status is useful to let our coworker know about our current state:

- being on holidays
- doing a training
- working hard 😎 

Some of those could be automated for specific Forecast projects. For example when I'm off, I would like my status to automatically switch to **🌴 Vacationing** so people know to not expect an answer right away. It's kind of the same for some very specific Forecast projects like **training**, **conferences**...

A Slack team can setup preset for statuses:

![image](https://user-images.githubusercontent.com/225704/93920385-693a8100-fd0f-11ea-9229-aa4ef26a6728.png)

And statuses have a lifetime so if I'm off for two days the status should be set to disappear two days later:

![image](https://user-images.githubusercontent.com/225704/93920466-840cf580-fd0f-11ea-892d-aa050256d928.png)

**Comment by lyrixx** [comment]
Would you mind to submit a PR?

**Comment by xavierlacot** [comment]
This project is now archived. Some recent additions to Forecast tools are only useful in the context of JoliCode, and are far too specific to be shared in an open product. For this reason, we will continue the development of Forecast tools, but as a closed source product. This repository remains online but archived.
